# Default values for supersimplechart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: neilghosh/super-simple-svc
  tag: v1

service:
  type: ClusterIP
  port: 80


