apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supersimplechart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "supersimplechart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "supersimplechart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 80